### ISSUE TITLE
Parameter propagation and error checks

### ISSUE THREAD

**Issue by khufkens** [geco-bern/rsofun#100]
@stineb When fewer parameters than the default 5 are provided how are the rest of these set (or routines ignored which require these inputs).

Are there checks in place to see if this is so at the FORTRAN level (not so at any higher level as far was we can tell).

@pepaaran

**Comment by stineb** [comment]
The FORTRAN part is rigid in its treatment of parameters. It always expects the same length (say N) of the vector `par` which contains the (calibratable) parameters. In setups where fewer than N parameters are accounted for in the calibration, the remaining parameters are now set in the cost functions that runs the model.

**Comment by khufkens** [comment]
In short, there are no checks in place that trap you feeding in the wrong number of parameters (given the settings in params_siml specifying the soil and temperature response). Basically you can have these set as TRUE (running the function) but only specify kphio and still get a result (of sorts). These can be basic copy paste errors that propagate.

**Comment by khufkens** [comment]
- [ ] error trap NULL (no parameters)
- [ ] error trap inconsistent parameters between those provided and the simulation setup
- [ ] named parameters might be required or outputs dependent on the `params_siml` settings

**Comment by pepaaran** [comment]
Since pull request #102 there's an error trap in run_pmodel_f_bysite() that checks:
- if params_modl = NULL
- if kphio is missing ( this must always be present)
- when params_siml$soilmstress = TRUE, if soilm_par_a or soilm_par_b are missing
- when params_siml$tempstress = tRUE, if tau and shape are missing

When something of the above fails, run_pmodel_f_bysite() returns a dataframe of NAs. That way we avoid the mismatch of settings and fed parameters but if more parameters than needed are fed, it still gives a result.

**Comment by pepaaran** [comment]
@stineb Is there any reason why we need to return NA's in run_pmodel_f_bysite()? If we don't need it, it's more correct to have a stop condiition and return NULL with an error/warning message, so I would refactor this.

**Comment by khufkens** [comment]
This should all be resolved as of #140
