### ISSUE TITLE
remove spurious dependencies

### ISSUE THREAD

**Issue by khufkens** [geco-bern/rsofun#106]
Remove unwanted dependencies:

- [x] move to R >= 4.2 replace %>% with |> (drop magrittr)
- [ ] remove lubridate and fall back to POSIX dates and format()
- [ ] remove graphics (only used in disfunctional methods)

**Comment by khufkens** [comment]
If this would work, yes. I think, especially in this case where these changes don't touch too many functions it is worth the effort (ingestr in this respect is another matter for example). Also, combining rowwise() and or do() statements could probably have the same effect, sticking to only {dplyr} routines.

**Comment by pepaaran** [comment]
I saw that `dplyr` imports `magrittr`. Since we'll be depending on `magrittr` anyways, I don't think it makes much sense to remove `%>%` because we wouldn't remove the dependency and it complicates the parallelization quite a bit. I'm struggling to move the parallelized operations on tibbles to base R because of the row-wise operations.

**Comment by khufkens** [comment]
Thanks for trying.

**Comment by khufkens** [comment]
Closing, fixed to the extend possible
