### ISSUE TITLE
Call for a feature freeze until (CRAN) publication/submission

### ISSUE THREAD

**Issue by khufkens** [geco-bern/rsofun#170]
@stineb @pepaaran 

There has been a lot of activity on the repo the past few weeks, mostly this is not related to finishing CRAN compliance, but rather with adding new features. I strongly suggest a feature freeze until publication on the master branch. The bragging rights of adding additional functionality does not weigh against the continued burden of maintenance to CRAN specs and required adjustments on the manuscript and documentation side. In practice this would mean not publishing the CN branch.

**Comment by stineb** [comment]
Agreed. The latest changes were almost exclusively for cleaning up the input and output example data and documentation. This involved lots of changes, indeed, but I think they were necessary to be completed before we publish. This will also make our lives easier in the future since documentation is now more coherent and reflective of what the model needs and returns.

Regarding the `cnmodel` branch: This was not intended to be published now. Can we just leave it in the branch? I know, ideally it's in a branch of my own fork, but it would avoid having to delete the geco-bern/rsofun `cnmodel` branch.

**Comment by khufkens** [comment]
cnmodel stays in the branch - but I will close the #164 pull request for now.
