### ISSUE TITLE
test-coverage keeps failing

### ISSUE THREAD

**Issue by pepaaran** [geco-bern/rsofun#178]
Almost in all instances, the `test-coverage` check fails. It's always the same error:

```
Running ‘testthat.R’
Error: Error in readRDS(f) : error reading from connection
Calls: <Anonymous> ... merge_coverage.character -> lapply -> FUN -> as.list
Execution halted
```

In all other checks, the unit tests in the `tests/testthat/` folder don't give any issues. I've done some searching but cannot pin point the issue. In [this issue from the `testthat` package](https://github.com/r-lib/testthat/issues/1740#issuecomment-1481125901), they say that `test_check()` may not be the best function to use for package tests and in the documentation for `test_check` it says that it's only to run the tests during R CMD checks. @khufkens do you have any experience with this? 

On another note, the code coverage went down from ~93% to ~76%, but I have no idea why. Is this relevant for the submission or should I let it be as is?

**Comment by khufkens** [comment]
Most likely a `covr` issue. Note that the tests run fine as displayed here:

https://github.com/geco-bern/rsofun/actions/runs/6470788865/job/17567759154?pr=177

It is the uploading or compiling of the code coverage (how many lines are touched during tests) that fail on:
`Calls: <Anonymous> ... merge_coverage.character -> lapply -> FUN -> as.list`

The decreased coverage is due to Fortran code, I'm not sure what changed there:
https://app.codecov.io/gh/geco-bern/rsofun

Less code coverage is not bad, but I generally like to keep things above 85% - not relevant for submission though - more my relentless nature to keep things from going stale (code not covered in tests is "invisible" often has no use and therefore should be removed or kept in a fork until mature enough IMO).

You probably read up on some of that for agile, write your documentation / unit tests first. That's why.

**Comment by pepaaran** [comment]
Okay, so I will just update that the code coverage is reduced and not modify the tests. How can I trigger test-coverage manually? Thanks for the help!

**Comment by khufkens** [comment]
Under Actions, go to the instance for test-coverage:

![Screenshot from 2023-10-11 15-44-03](https://github.com/geco-bern/rsofun/assets/1354258/61a85fa0-d8c6-4c87-81d3-04e40d2b613f)

Top right you can `Re-run jobs`

Not sure you can trigger this. Let me know than I can give you admin permissions (but best not to change your workflow - work on your side).

**Comment by pepaaran** [comment]
Thanks, I can run it on my fork. It's the same workflow as the geco-group branch uses.

**Comment by pepaaran** [comment]
Now it passed without errors. There are still some warnings but I guess that's negligible. I'll go ahead and resubmit to CRAN.

**Comment by khufkens** [comment]
Only catching this now, yes always let them know what you fixed!
