### ISSUE TITLE
Repeat last year of forcing

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#275]
Repeat last year of forcing when `nyeartrend` is greater than number of years in forcing.

This is needed for LULUC, and is the behavior I would expect as a user. As of today, the code just crashes silently.

**Comment by fabern** [comment]
What a timing, I'm literally looking at this at the moment. :smile: 

So this was implemented only in #276?
Strange, because I'm on an earlier version and don't get a crash. So I was wondering what was used in my case. I will need to dive deeper then.

Side note regarding expected behavior: this can be very variable depending on user background. (I personally would expect an error message.) As a bottom line, best is to assume as little as possible about the users expectations.

- [ ] Do we have a mechanism to give out warnings explaining what was used to extrapolate the time series? This can be valuable to spot mistakes when setting up simulations.

**Comment by marcadella** [comment]
In P-model it won't really do anything since nyeartrend is set internally by the R layer by looking at the size of the forcing array. In Biomee, Fortran would crash silently and R would fill the output with NA.

**Comment by fabern** [comment]
> In Biomee, Fortran would crash silently and R would fill the output with NA.

Ah, okay. Yes `NA`, that's what's happening in my case. Good then that's solved.

I thought that the PR #276 is adding that behavior for P-model, too? No. Then I must have misunderstood. We can further discuss this in PR #276.

**Comment by marcadella** [comment]
No change for P-model.
